# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 655)
        MainWindow.setTabletTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 2)
        self.feelslike = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.feelslike.setFont(font)
        self.feelslike.setReadOnly(True)
        self.feelslike.setObjectName("feelslike")
        self.gridLayout.addWidget(self.feelslike, 5, 3, 1, 2)
        self.max_temp = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.max_temp.setFont(font)
        self.max_temp.setReadOnly(True)
        self.max_temp.setObjectName("max_temp")
        self.gridLayout.addWidget(self.max_temp, 6, 4, 1, 1)
        self.humidity = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.humidity.setFont(font)
        self.humidity.setReadOnly(True)
        self.humidity.setObjectName("humidity")
        self.gridLayout.addWidget(self.humidity, 8, 3, 1, 2)
        self.get = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.get.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get.setIcon(icon)
        self.get.setIconSize(QtCore.QSize(25, 25))
        self.get.setObjectName("get")
        self.gridLayout.addWidget(self.get, 1, 1, 1, 4)
        self.angle = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.angle.setFont(font)
        self.angle.setReadOnly(True)
        self.angle.setObjectName("angle")
        self.gridLayout.addWidget(self.angle, 9, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 2)
        self.speed = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.speed.setFont(font)
        self.speed.setReadOnly(True)
        self.speed.setObjectName("speed")
        self.gridLayout.addWidget(self.speed, 9, 3, 1, 1)
        self.pressure = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pressure.setFont(font)
        self.pressure.setReadOnly(True)
        self.pressure.setObjectName("pressure")
        self.gridLayout.addWidget(self.pressure, 7, 3, 1, 2)
        self.min_temp = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.min_temp.setFont(font)
        self.min_temp.setReadOnly(True)
        self.min_temp.setObjectName("min_temp")
        self.gridLayout.addWidget(self.min_temp, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.city = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.city.setFont(font)
        self.city.setTabletTracking(True)
        self.city.setText("")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setReadOnly(False)
        self.city.setObjectName("city")
        self.gridLayout_3.addWidget(self.city, 1, 2, 1, 1)
        self.country = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.country.setFont(font)
        self.country.setTabletTracking(True)
        self.country.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.country.setText("")
        self.country.setAlignment(QtCore.Qt.AlignCenter)
        self.country.setReadOnly(False)
        self.country.setObjectName("country")
        self.gridLayout_3.addWidget(self.country, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 5)
        self.description = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.description.setText("")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 2, 1, 1, 4)
        self.maintemp = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.maintemp.setFont(font)
        self.maintemp.setText("")
        self.maintemp.setReadOnly(True)
        self.maintemp.setObjectName("maintemp")
        self.gridLayout.addWidget(self.maintemp, 4, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.me = QtWidgets.QMenu(self.menuMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/me.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.me.setIcon(icon1)
        self.me.setObjectName("me")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon2)
        self.exit.setObjectName("exit")
        self.getac = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icons/do.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getac.setIcon(icon3)
        self.getac.setObjectName("getac")
        self.help = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icons/new_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon4)
        self.help.setObjectName("help")
        self.name = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./icons/name.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.name.setIcon(icon5)
        self.name.setObjectName("name")
        self.phone = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./icons/mob.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phone.setIcon(icon6)
        self.phone.setObjectName("phone")
        self.me.addAction(self.name)
        self.me.addSeparator()
        self.me.addAction(self.phone)
        self.me.addSeparator()
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.getac)
        self.menuMenu.addAction(self.me.menuAction())
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.help)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.exit)
        self.menuMenu.addSeparator()
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.exit.triggered.connect(MainWindow.close)
        self.getac.triggered.connect(self.get.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.country, self.city)
        MainWindow.setTabOrder(self.city, self.get)
        MainWindow.setTabOrder(self.get, self.maintemp)
        MainWindow.setTabOrder(self.maintemp, self.feelslike)
        MainWindow.setTabOrder(self.feelslike, self.min_temp)
        MainWindow.setTabOrder(self.min_temp, self.max_temp)
        MainWindow.setTabOrder(self.max_temp, self.pressure)
        MainWindow.setTabOrder(self.pressure, self.humidity)
        MainWindow.setTabOrder(self.humidity, self.speed)
        MainWindow.setTabOrder(self.speed, self.angle)
        MainWindow.setTabOrder(self.angle, self.description)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.label_5.setText(_translate("MainWindow", "main temperature"))
        self.label_9.setText(_translate("MainWindow", "pressure"))
        self.feelslike.setStatusTip(_translate("MainWindow", "temperature feels like"))
        self.max_temp.setStatusTip(_translate("MainWindow", "minimum temp"))
        self.humidity.setStatusTip(_translate("MainWindow", "the humidity"))
        self.get.setStatusTip(_translate("MainWindow", "click to get weather"))
        self.get.setText(_translate("MainWindow", "get weather"))
        self.angle.setStatusTip(_translate("MainWindow", "wnd angle "))
        self.label_10.setText(_translate("MainWindow", "humidity"))
        self.label_3.setText(_translate("MainWindow", "Weather : "))
        self.label_7.setText(_translate("MainWindow", "min and max temp"))
        self.speed.setStatusTip(_translate("MainWindow", "wind speed"))
        self.pressure.setStatusTip(_translate("MainWindow", "pressure"))
        self.min_temp.setStatusTip(_translate("MainWindow", "maximum temp"))
        self.label_6.setText(_translate("MainWindow", "feels like"))
        self.groupBox.setTitle(_translate("MainWindow", "Location"))
        self.label_2.setText(_translate("MainWindow", "country"))
        self.city.setStatusTip(_translate("MainWindow", "enter your city here"))
        self.country.setStatusTip(_translate("MainWindow", "enter your country here"))
        self.label.setText(_translate("MainWindow", "city"))
        self.description.setStatusTip(_translate("MainWindow", "weather status"))
        self.maintemp.setStatusTip(_translate("MainWindow", "the main temperature"))
        self.label_8.setText(_translate("MainWindow", "wind speed and angle"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.me.setTitle(_translate("MainWindow", "About me"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.exit.setStatusTip(_translate("MainWindow", "quit the application"))
        self.exit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.getac.setText(_translate("MainWindow", "get weather"))
        self.getac.setStatusTip(_translate("MainWindow", "get the weather"))
        self.getac.setShortcut(_translate("MainWindow", "Return"))
        self.help.setText(_translate("MainWindow", "help"))
        self.help.setStatusTip(_translate("MainWindow", "information about the application"))
        self.help.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.name.setText(_translate("MainWindow", "name"))
        self.name.setStatusTip(_translate("MainWindow", "developer name"))
        self.name.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.phone.setText(_translate("MainWindow", "phone"))
        self.phone.setStatusTip(_translate("MainWindow", "developer phone number"))
        self.phone.setShortcut(_translate("MainWindow", "Ctrl+P"))
